stages:
  - build
  - test
  - deploy

build:gcc-4.9:
  stage: build
  image: bernddoser/docker-devel-cpp:ubuntu-16.04-gcc-4.9-tools-1
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DGTEST_ROOT=/opt/googletest-1.8.0 ..
    - make -j
    
build:gcc-6:
  stage: build
  image: bernddoser/docker-devel-cpp:ubuntu-16.04-gcc-6-tools-1
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DGTEST_ROOT=/opt/googletest-1.8.0 ..
    - make -j
    
#build:clang-3.9:
#  stage: build
#  image: bernddoser/docker-devel-cpp:ubuntu-16.04-clang-3.9-tools-1
#  script:
#    - mkdir build
#    - cd build
#    - cmake -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DGTEST_ROOT=/opt/googletest-1.8.0 ..
#    - make -j
    
test:gcc-4.9:
  stage: test
  image: bernddoser/docker-devel-cpp:ubuntu-16.04-gcc-4.9-tools-1
  dependencies:
    - build:gcc-4.9
  script:
    - cd build
    - make test
  artifacts:
    paths:
      - build

deploy:gcc-4.9:
  stage: deploy
  image: bernddoser/docker-devel-cpp:ubuntu-16.04-gcc-4.9-tools-1
  dependencies:
    - test:gcc-4.9
  script:
    - cd build
    - make package
  artifacts:
    paths:
      - BlasBooster-*-Linux.tar.gz
  when: manual