stages:
  - build
  - test
  - deploy

build_job:gcc-4.9:
  stage: build
  image: bernddoser/docker-devel-cpp:ubuntu-16.04-gcc-4.9
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++ ..
    - make -j
    
build_job:gcc-6:
  stage: build
  image: bernddoser/docker-devel-cpp:ubuntu-16.04-gcc-6
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++ ..
    - make -j
    
build_job:clang-3.9:
  stage: build
  image: bernddoser/docker-devel-cpp:ubuntu-16.04-clang-3.9
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=/usr/bin/clang++ ..
    - make -j
    
test_job:
  stage: test
  script:
    - make test

deploy_job:
  stage: deploy
  script:
    - make deploy
  when: manual