test:gcc-4.9:
  image: nercury/cmake-cpp:gcc-4.9
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j
    
test:gcc-6.1:
  image: nercury/cmake-cpp:gcc-6.1
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j