#ifndef BLASBOOSTER_MACRO_CREATE_BLAS_FUNCTION_TYPE_H_
#define BLASBOOSTER_MACRO_CREATE_BLAS_FUNCTION_TYPE_H_

#include "BlasBoosterMacroCreateSingleBlasFunctionType.h"
#include "BlasBoosterMacroBlasFunctionList.h"
#include <boost/preprocessor/seq/for_each.hpp>

#define BLASBOOSTER_MACRO_CREATE_BLAS_FUNCTION_TYPE()\
    BOOST_PP_SEQ_FOR_EACH(BLASBOOSTER_MACRO_CREATE_SINGLE_BLAS_FUNCTION_TYPE,,BLASBOOSTER_MACRO_BLAS_FUNCTION_LIST)

#endif /* BLASBOOSTER_MACRO_CREATE_BLAS_FUNCTION_TYPE_H_ */
