#pragma once

#include <complex>

extern "C" {

float scabs1_(const std::complex<float>*);
float sasum_(const int*, const float*, const int*);
void saxpy_(const int*, const float*, const float*, const int*, float*, const int*);
void saxpby_(const int*, const float*, const float*, const int*, const float*, float*, const int*);
float scasum_(const int*, const std::complex<float>*, const int*);
float scnrm2_(const int*, const std::complex<float>*, const int*);
void scopy_(const int*, const float*, const int*, float*, const int*);
float sdot_(const int*, const float*, const int*, const float*, const int*);
float sdsdot_(const int*, const float*, const float*, const int*, const float*, const int*);
float snrm2_(const int*, const float*, const int*);
void srot_(const int*, float*, const int*, float*, const int*, const float*, const float*);
void srotg_(float*, float*, float*, float*);
void srotm_(const int*, float*, const int*, float*, const int*, const float*);
void srotmg_(float*, float*, float*, const float*, float*);
void sscal_(const int*, const float*, float*, const int*);
void sswap_(const int*, float*, const int*, float*, const int*);
int isamax_(const int*, const float*, const int*);
int isamin_(const int*, const float*, const int*);
void caxpy_(const int*, const std::complex<float>*, const std::complex<float>*, const int*, std::complex<float>*, const int*);
void caxpby_(const int*, const std::complex<float>*, const std::complex<float>*, const int*, const std::complex<float>*, std::complex<float>*, const int*);
void ccopy_(const int*, const std::complex<float>*, const int*, std::complex<float>*, const int*);
void crotg_(std::complex<float>*, const std::complex<float>*, float*, std::complex<float>*);
void cscal_(const int*, const std::complex<float>*, std::complex<float>*, const int*);
void csrot_(const int*, std::complex<float>*, const int*, std::complex<float>*, const int*, const float*, const float*);
void csscal_(const int*, const float*, std::complex<float>*, const int*);
void cswap_(const int*, std::complex<float>*, const int*, std::complex<float>*, const int*);
int icamax_(const int*, const std::complex<float>*, const int*);
int icamin_(const int*, const std::complex<float>*, const int*);
double dcabs1_(const std::complex<double>*);
double dasum_(const int*, const double*, const int*);
void daxpy_(const int*, const double*, const double*, const int*, double*, const int*);
void daxpby_(const int*, const double*, const double*, const int*, const double*, double*, const int*);
void dcopy_(const int*, const double*, const int*, double*, const int*);
double ddot_(const int*, const double*, const int*, const double*, const int*);
double dsdot_(const int*, const float*, const int*, const float*, const int*);
double dnrm2_(const int*, const double*, const int*);
void drot_(const int*, double*, const int*, double*, const int*, const double*, const double*);
void drotg_(double*, double*, double*, double*);
void drotm_(const int*, double*, const int*, double*, const int*, const double*);
void drotmg_(double*, double*, double*, const double*, double*);
void dscal_(const int*, const double*, double*, const int*);
void dswap_(const int*, double*, const int*, double*, const int*);
double dzasum_(const int*, const std::complex<double>*, const int*);
double dznrm2_(const int*, const std::complex<double>*, const int*);
int idamax_(const int*, const double*, const int*);
int idamin_(const int*, const double*, const int*);
void zaxpy_(const int*, const std::complex<double>*, const std::complex<double>*, const int*, std::complex<double>*, const int*);
void zaxpby_(const int*, const std::complex<double>*, const std::complex<double>*, const int*, const std::complex<double>*, std::complex<double>*, const int*);
void zcopy_(const int*, const std::complex<double>*, const int*, std::complex<double>*, const int*);
void zdrot_(const int*, std::complex<double>*, const int*, std::complex<double>*, const int*, const double*, const double*);
void zdscal_(const int*, const double*, std::complex<double>*, const int*);
void zrotg_(std::complex<double>*, const std::complex<double>*, double*, std::complex<double>*);
void zscal_(const int*, const std::complex<double>*, std::complex<double>*, const int*);
void zswap_(const int*, std::complex<double>*, const int*, std::complex<double>*, const int*);
int izamax_(const int*, const std::complex<double>*, const int*);
int izamin_(const int*, const std::complex<double>*, const int*);
void sgbmv_(const char*, const int*, const int*, const int*, const int*, const float*, const float*, const int*, const float*, const int*, const float*, float*, const int*);
void sgemv_(const char*, const int*, const int*, const float*, const float*, const int*, const float*, const int*, const float*, float*, const int*);
void sger_(const int*, const int*, const float*, const float*, const int*, const float*, const int*, float*, const int*);
void ssbmv_(const char*, const int*, const int*, const float*, const float*, const int*, const float*, const int*, const float*, float*, const int*);
void sspmv_(const char*, const int*, const float*, const float*, const float*, const int*, const float*, float*, const int*);
void sspr_(const char*, const int*, const float*, const float*, const int*, float*);
void sspr2_(const char*, const int*, const float*, const float*, const int*, const float*, const int*, float*);
void ssymv_(const char*, const int*, const float*, const float*, const int*, const float*, const int*, const float*, float*, const int*);
void ssyr_(const char*, const int*, const float*, const float*, const int*, float*, const int*);
void ssyr2_(const char*, const int*, const float*, const float*, const int*, const float*, const int*, float*, const int*);
void stbmv_(const char*, const char*, const char*, const int*, const int*, const float*, const int*, float*, const int*);
void stbsv_(const char*, const char*, const char*, const int*, const int*, const float*, const int*, float*, const int*);
void stpmv_(const char*, const char*, const char*, const int*, const float*, float*, const int*);
void stpsv_(const char*, const char*, const char*, const int*, const float*, float*, const int*);
void strmv_(const char*, const char*, const char*, const int*, const float*, const int*, float*, const int*);
void strsv_(const char*, const char*, const char*, const int*, const float*, const int*, float*, const int*);
void cgbmv_(const char*, const int*, const int*, const int*, const int*, const std::complex<float>*, const std::complex<float>*, const int*, const std::complex<float>*, const int*, const std::complex<float>*, std::complex<float>*, const int*);
void cgemv_(const char*, const int*, const int*, const std::complex<float>*, const std::complex<float>*, const int*, const std::complex<float>*, const int*, const std::complex<float>*, std::complex<float>*, const int*);
void cgerc_(const int*, const int*, const std::complex<float>*, const std::complex<float>*, const int*, const std::complex<float>*, const int*, std::complex<float>*, const int*);
void cgeru_(const int*, const int*, const std::complex<float>*, const std::complex<float>*, const int*, const std::complex<float>*, const int*, std::complex<float>*, const int*);
void chbmv_(const char*, const int*, const int*, const std::complex<float>*, const std::complex<float>*, const int*, const std::complex<float>*, const int*, const std::complex<float>*, std::complex<float>*, const int*);
void chemv_(const char*, const int*, const std::complex<float>*, const std::complex<float>*, const int*, const std::complex<float>*, const int*, const std::complex<float>*, std::complex<float>*, const int*);
void cher_(const char*, const int*, const float*, const std::complex<float>*, const int*, std::complex<float>*, const int*);
void cher2_(const char*, const int*, const std::complex<float>*, const std::complex<float>*, const int*, const std::complex<float>*, const int*, std::complex<float>*, const int*);
void chpmv_(const char*, const int*, const std::complex<float>*, const std::complex<float>*, const std::complex<float>*, const int*, const std::complex<float>*, std::complex<float>*, const int*);
void chpr_(const char*, const int*, const float*, const std::complex<float>*, const int*, std::complex<float>*);
void chpr2_(const char*, const int*, const std::complex<float>*, const std::complex<float>*, const int*, const std::complex<float>*, const int*, std::complex<float>*);
void ctbmv_(const char*, const char*, const char*, const int*, const int*, const std::complex<float>*, const int*, std::complex<float>*, const int*);
void ctbsv_(const char*, const char*, const char*, const int*, const int*, const std::complex<float>*, const int*, std::complex<float>*, const int*);
void ctpmv_(const char*, const char*, const char*, const int*, const std::complex<float>*, std::complex<float>*, const int*);
void ctpsv_(const char*, const char*, const char*, const int*, const std::complex<float>*, std::complex<float>*, const int*);
void ctrmv_(const char*, const char*, const char*, const int*, const std::complex<float>*, const int*, std::complex<float>*, const int*);
void ctrsv_(const char*, const char*, const char*, const int*, const std::complex<float>*, const int*, std::complex<float>*, const int*);
void dgbmv_(const char*, const int*, const int*, const int*, const int*, const double*, const double*, const int*, const double*, const int*, const double*, double*, const int*);
void dgemv_(const char*, const int*, const int*, const double*, const double*, const int*, const double*, const int*, const double*, double*, const int*);
void dger_(const int*, const int*, const double*, const double*, const int*, const double*, const int*, double*, const int*);
void dsbmv_(const char*, const int*, const int*, const double*, const double*, const int*, const double*, const int*, const double*, double*, const int*);
void dspmv_(const char*, const int*, const double*, const double*, const double*, const int*, const double*, double*, const int*);
void dspr_(const char*, const int*, const double*, const double*, const int*, double*);
void dspr2_(const char*, const int*, const double*, const double*, const int*, const double*, const int*, double*);
void dsymv_(const char*, const int*, const double*, const double*, const int*, const double*, const int*, const double*, double*, const int*);
void dsyr_(const char*, const int*, const double*, const double*, const int*, double*, const int*);
void dsyr2_(const char*, const int*, const double*, const double*, const int*, const double*, const int*, double*, const int*);
void dtbmv_(const char*, const char*, const char*, const int*, const int*, const double*, const int*, double*, const int*);
void dtbsv_(const char*, const char*, const char*, const int*, const int*, const double*, const int*, double*, const int*);
void dtpmv_(const char*, const char*, const char*, const int*, const double*, double*, const int*);
void dtpsv_(const char*, const char*, const char*, const int*, const double*, double*, const int*);
void dtrmv_(const char*, const char*, const char*, const int*, const double*, const int*, double*, const int*);
void dtrsv_(const char*, const char*, const char*, const int*, const double*, const int*, double*, const int*);
void zgbmv_(const char*, const int*, const int*, const int*, const int*, const std::complex<double>*, const std::complex<double>*, const int*, const std::complex<double>*, const int*, const std::complex<double>*, std::complex<double>*, const int*);
void zgemv_(const char*, const int*, const int*, const std::complex<double>*, const std::complex<double>*, const int*, const std::complex<double>*, const int*, const std::complex<double>*, std::complex<double>*, const int*);
void zgerc_(const int*, const int*, const std::complex<double>*, const std::complex<double>*, const int*, const std::complex<double>*, const int*, std::complex<double>*, const int*);
void zgeru_(const int*, const int*, const std::complex<double>*, const std::complex<double>*, const int*, const std::complex<double>*, const int*, std::complex<double>*, const int*);
void zhbmv_(const char*, const int*, const int*, const std::complex<double>*, const std::complex<double>*, const int*, const std::complex<double>*, const int*, const std::complex<double>*, std::complex<double>*, const int*);
void zhemv_(const char*, const int*, const std::complex<double>*, const std::complex<double>*, const int*, const std::complex<double>*, const int*, const std::complex<double>*, std::complex<double>*, const int*);
void zher_(const char*, const int*, const double*, const std::complex<double>*, const int*, std::complex<double>*, const int*);
void zher2_(const char*, const int*, const std::complex<double>*, const std::complex<double>*, const int*, const std::complex<double>*, const int*, std::complex<double>*, const int*);
void zhpmv_(const char*, const int*, const std::complex<double>*, const std::complex<double>*, const std::complex<double>*, const int*, const std::complex<double>*, std::complex<double>*, const int*);
void zhpr_(const char*, const int*, const double*, const std::complex<double>*, const int*, std::complex<double>*);
void zhpr2_(const char*, const int*, const std::complex<double>*, const std::complex<double>*, const int*, const std::complex<double>*, const int*, std::complex<double>*);
void ztbmv_(const char*, const char*, const char*, const int*, const int*, const std::complex<double>*, const int*, std::complex<double>*, const int*);
void ztbsv_(const char*, const char*, const char*, const int*, const int*, const std::complex<double>*, const int*, std::complex<double>*, const int*);
void ztpmv_(const char*, const char*, const char*, const int*, const std::complex<double>*, std::complex<double>*, const int*);
void ztpsv_(const char*, const char*, const char*, const int*, const std::complex<double>*, std::complex<double>*, const int*);
void ztrmv_(const char*, const char*, const char*, const int*, const std::complex<double>*, const int*, std::complex<double>*, const int*);
void ztrsv_(const char*, const char*, const char*, const int*, const std::complex<double>*, const int*, std::complex<double>*, const int*);
void sgemm_(const char*, const char*, const int*, const int*, const int*, const float*, const float*, const int*, const float*, const int*, const float*, float*, const int*);
void ssymm_(const char*, const char*, const int*, const int*, const float*, const float*, const int*, const float*, const int*, const float*, float*, const int*);
void ssyr2k_(const char*, const char*, const int*, const int*, const float*, const float*, const int*, const float*, const int*, const float*, float*, const int*);
void ssyrk_(const char*, const char*, const int*, const int*, const float*, const float*, const int*, const float*, float*, const int*);
void strmm_(const char*, const char*, const char*, const char*, const int*, const int*, const float*, const float*, const int*, float*, const int*);
void strsm_(const char*, const char*, const char*, const char*, const int*, const int*, const float*, const float*, const int*, float*, const int*);
void cgemm_(const char*, const char*, const int*, const int*, const int*, const std::complex<float>*, const std::complex<float>*, const int*, const std::complex<float>*, const int*, const std::complex<float>*, std::complex<float>*, const int*);
void cgemm3m_(const char*, const char*, const int*, const int*, const int*, const std::complex<float>*, const std::complex<float>*, const int*, const std::complex<float>*, const int*, const std::complex<float>*, std::complex<float>*, const int*);
void chemm_(const char*, const char*, const int*, const int*, const std::complex<float>*, const std::complex<float>*, const int*, const std::complex<float>*, const int*, const std::complex<float>*, std::complex<float>*, const int*);
void cher2k_(const char*, const char*, const int*, const int*, const std::complex<float>*, const std::complex<float>*, const int*, const std::complex<float>*, const int*, const float*, std::complex<float>*, const int*);
void cherk_(const char*, const char*, const int*, const int*, const float*, const std::complex<float>*, const int*, const float*, std::complex<float>*, const int*);
void csymm_(const char*, const char*, const int*, const int*, const std::complex<float>*, const std::complex<float>*, const int*, const std::complex<float>*, const int*, const std::complex<float>*, std::complex<float>*, const int*);
void csyr2k_(const char*, const char*, const int*, const int*, const std::complex<float>*, const std::complex<float>*, const int*, const std::complex<float>*, const int*, const std::complex<float>*, std::complex<float>*, const int*);
void csyrk_(const char*, const char*, const int*, const int*, const std::complex<float>*, const std::complex<float>*, const int*, const std::complex<float>*, std::complex<float>*, const int*);
void ctrmm_(const char*, const char*, const char*, const char*, const int*, const int*, const std::complex<float>*, const std::complex<float>*, const int*, std::complex<float>*, const int*);
void ctrsm_(const char*, const char*, const char*, const char*, const int*, const int*, const std::complex<float>*, const std::complex<float>*, const int*, std::complex<float>*, const int*);
void dgemm_(const char*, const char*, const int*, const int*, const int*, const double*, const double*, const int*, const double*, const int*, const double*, double*, const int*);
void dsymm_(const char*, const char*, const int*, const int*, const double*, const double*, const int*, const double*, const int*, const double*, double*, const int*);
void dsyr2k_(const char*, const char*, const int*, const int*, const double*, const double*, const int*, const double*, const int*, const double*, double*, const int*);
void dsyrk_(const char*, const char*, const int*, const int*, const double*, const double*, const int*, const double*, double*, const int*);
void dtrmm_(const char*, const char*, const char*, const char*, const int*, const int*, const double*, const double*, const int*, double*, const int*);
void dtrsm_(const char*, const char*, const char*, const char*, const int*, const int*, const double*, const double*, const int*, double*, const int*);
void zgemm_(const char*, const char*, const int*, const int*, const int*, const std::complex<double>*, const std::complex<double>*, const int*, const std::complex<double>*, const int*, const std::complex<double>*, std::complex<double>*, const int*);
void zgemm3m_(const char*, const char*, const int*, const int*, const int*, const std::complex<double>*, const std::complex<double>*, const int*, const std::complex<double>*, const int*, const std::complex<double>*, std::complex<double>*, const int*);
void zhemm_(const char*, const char*, const int*, const int*, const std::complex<double>*, const std::complex<double>*, const int*, const std::complex<double>*, const int*, const std::complex<double>*, std::complex<double>*, const int*);
void zher2k_(const char*, const char*, const int*, const int*, const std::complex<double>*, const std::complex<double>*, const int*, const std::complex<double>*, const int*, const double*, std::complex<double>*, const int*);
void zherk_(const char*, const char*, const int*, const int*, const double*, const std::complex<double>*, const int*, const double*, std::complex<double>*, const int*);
void zsymm_(const char*, const char*, const int*, const int*, const std::complex<double>*, const std::complex<double>*, const int*, const std::complex<double>*, const int*, const std::complex<double>*, std::complex<double>*, const int*);
void zsyr2k_(const char*, const char*, const int*, const int*, const std::complex<double>*, const std::complex<double>*, const int*, const std::complex<double>*, const int*, const std::complex<double>*, std::complex<double>*, const int*);
void zsyrk_(const char*, const char*, const int*, const int*, const std::complex<double>*, const std::complex<double>*, const int*, const std::complex<double>*, std::complex<double>*, const int*);
void ztrmm_(const char*, const char*, const char*, const char*, const int*, const int*, const std::complex<double>*, const std::complex<double>*, const int*, std::complex<double>*, const int*);
void ztrsm_(const char*, const char*, const char*, const char*, const int*, const int*, const std::complex<double>*, const std::complex<double>*, const int*, std::complex<double>*, const int*);

void cdotc_(std::complex<float>*, const int*, const std::complex<float>*, const int*, const std::complex<float>*, const int*);
void cdotu_(std::complex<float>*, const int*, const std::complex<float>*, const int*, const std::complex<float>*, const int*);
void zdotc_(std::complex<double>*, const int*, const std::complex<double>*, const int*, const std::complex<double>*, const int*);
void zdotu_(std::complex<double>*, const int*, const std::complex<double>*, const int*, const std::complex<double>*, const int*);

} // extern "C"