#ifndef BLASBOOSTER_MACRO_CREATE_BLAS_FUNCTION_DEFINITION_FOR_INTERFACE_H_
#define BLASBOOSTER_MACRO_CREATE_BLAS_FUNCTION_DEFINITION_FOR_INTERFACE_H_

#include "BlasBoosterMacroCreateSingleBlasFunctionDefinitionForInterface.h"
#include <boost/preprocessor/seq/for_each.hpp>

#define BLASBOOSTER_MACRO_CREATE_BLAS_FUNCTION_DEFINITION_FOR_INTERFACE(INTERFACE, BLAS_FUNCTION_PREFIX, BLAS_FUNCTION_LIST)\
    BOOST_PP_SEQ_FOR_EACH(\
    	BLASBOOSTER_MACRO_CREATE_SINGLE_BLAS_FUNCTION_DEFINITION_FOR_INTERFACE,\
		(INTERFACE, BLAS_FUNCTION_PREFIX),\
        BLAS_FUNCTION_LIST)

#endif // BLASBOOSTER_MACRO_CREATE_BLAS_FUNCTION_DEFINITION_FOR_INTERFACE_H_
