#pragma once

#include <complex>

extern "C" {

scabs1_(const std::complex<float>);
sasum_(const int, const float, const int);
saxpy_(const int, const float, const float, const int, float, const int);
saxpby_(const int, const float, const float, const int, const float, float, const int);
saxpyi_(const int, const float, const float, const int, float);
scasum_(const int, const std::complex<float>, const int);
scnrm2_(const int, const std::complex<float>, const int);
scopy_(const int, const float, const int, float, const int);
sdot_(const int, const float, const int, const float, const int);
sdoti_(const int, const float, const int, const float);
sdsdot_(const int, const float, const float, const int, const float, const int);
sgthr_(const int, const float, float, const int);
sgthrz_(const int, float, float, const int);
snrm2_(const int, const float, const int);
srot_(const int, float, const int, float, const int, const float, const float);
srotg_(float, float, float, float);
sroti_(const int, float, const int, float, const float, const float);
srotm_(const int, float, const int, float, const int, const float);
srotmg_(float, float, float, const float, float);
sscal_(const int, const float, float, const int);
ssctr_(const int, const float, const int, float);
sswap_(const int, float, const int, float, const int);
isamax_(const int, const float, const int);
isamin_(const int, const float, const int);
caxpy_(const int, const std::complex<float>, const std::complex<float>, const int, std::complex<float>, const int);
caxpby_(const int, const std::complex<float>, const std::complex<float>, const int, const std::complex<float>, std::complex<float>, const int);
caxpyi_(const int, const std::complex<float>, const std::complex<float>, const int, std::complex<float>);
ccopy_(const int, const std::complex<float>, const int, std::complex<float>, const int);
cgthr_(const int, const std::complex<float>, std::complex<float>, const int);
cgthrz_(const int, std::complex<float>, std::complex<float>, const int);
crotg_(std::complex<float>, const std::complex<float>, float, std::complex<float>);
cscal_(const int, const std::complex<float>, std::complex<float>, const int);
csctr_(const int, const std::complex<float>, const int, std::complex<float>);
csrot_(const int, std::complex<float>, const int, std::complex<float>, const int, const float, const float);
csscal_(const int, const float, std::complex<float>, const int);
cswap_(const int, std::complex<float>, const int, std::complex<float>, const int);
icamax_(const int, const std::complex<float>, const int);
icamin_(const int, const std::complex<float>, const int);
dcabs1_(const std::complex<double>);
dasum_(const int, const double, const int);
daxpy_(const int, const double, const double, const int, double, const int);
daxpby_(const int, const double, const double, const int, const double, double, const int);
daxpyi_(const int, const double, const double, const int, double);
dcopy_(const int, const double, const int, double, const int);
ddot_(const int, const double, const int, const double, const int);
dsdot_(const int, const float, const int, const float, const int);
ddoti_(const int, const double, const int, const double);
dgthr_(const int, const double, double, const int);
dgthrz_(const int, double, double, const int);
dnrm2_(const int, const double, const int);
drot_(const int, double, const int, double, const int, const double, const double);
drotg_(double, double, double, double);
droti_(const int, double, const int, double, const double, const double);
drotm_(const int, double, const int, double, const int, const double);
drotmg_(double, double, double, const double, double);
dscal_(const int, const double, double, const int);
dsctr_(const int, const double, const int, double);
dswap_(const int, double, const int, double, const int);
dzasum_(const int, const std::complex<double>, const int);
dznrm2_(const int, const std::complex<double>, const int);
idamax_(const int, const double, const int);
idamin_(const int, const double, const int);
zaxpy_(const int, const std::complex<double>, const std::complex<double>, const int, std::complex<double>, const int);
zaxpby_(const int, const std::complex<double>, const std::complex<double>, const int, const std::complex<double>, std::complex<double>, const int);
zaxpyi_(const int, const std::complex<double>, const std::complex<double>, const int, std::complex<double>);
zcopy_(const int, const std::complex<double>, const int, std::complex<double>, const int);
zdrot_(const int, std::complex<double>, const int, std::complex<double>, const int, const double, const double);
zdscal_(const int, const double, std::complex<double>, const int);
zgthr_(const int, const std::complex<double>, std::complex<double>, const int);
zgthrz_(const int, std::complex<double>, std::complex<double>, const int);
zrotg_(std::complex<double>, const std::complex<double>, double, std::complex<double>);
zscal_(const int, const std::complex<double>, std::complex<double>, const int);
zsctr_(const int, const std::complex<double>, const int, std::complex<double>);
zswap_(const int, std::complex<double>, const int, std::complex<double>, const int);
izamax_(const int, const std::complex<double>, const int);
izamin_(const int, const std::complex<double>, const int);
sgbmv_(const char, const int, const int, const int, const int, const float, const float, const int, const float, const int, const float, float, const int);
sgemv_(const char, const int, const int, const float, const float, const int, const float, const int, const float, float, const int);
sger_(const int, const int, const float, const float, const int, const float, const int, float, const int);
ssbmv_(const char, const int, const int, const float, const float, const int, const float, const int, const float, float, const int);
sspmv_(const char, const int, const float, const float, const float, const int, const float, float, const int);
sspr_(const char, const int, const float, const float, const int, float);
sspr2_(const char, const int, const float, const float, const int, const float, const int, float);
ssymv_(const char, const int, const float, const float, const int, const float, const int, const float, float, const int);
ssyr_(const char, const int, const float, const float, const int, float, const int);
ssyr2_(const char, const int, const float, const float, const int, const float, const int, float, const int);
stbmv_(const char, const char, const char, const int, const int, const float, const int, float, const int);
stbsv_(const char, const char, const char, const int, const int, const float, const int, float, const int);
stpmv_(const char, const char, const char, const int, const float, float, const int);
stpsv_(const char, const char, const char, const int, const float, float, const int);
strmv_(const char, const char, const char, const int, const float, const int, float, const int);
strsv_(const char, const char, const char, const int, const float, const int, float, const int);
sgem2vu_(const int, const int, const float, const float, const int, const float, const int, const float, const int, const float, float, const int, float, const int);
cgbmv_(const char, const int, const int, const int, const int, const std::complex<float>, const std::complex<float>, const int, const std::complex<float>, const int, const std::complex<float>, std::complex<float>, const int);
cgemv_(const char, const int, const int, const std::complex<float>, const std::complex<float>, const int, const std::complex<float>, const int, const std::complex<float>, std::complex<float>, const int);
cgerc_(const int, const int, const std::complex<float>, const std::complex<float>, const int, const std::complex<float>, const int, std::complex<float>, const int);
cgeru_(const int, const int, const std::complex<float>, const std::complex<float>, const int, const std::complex<float>, const int, std::complex<float>, const int);
chbmv_(const char, const int, const int, const std::complex<float>, const std::complex<float>, const int, const std::complex<float>, const int, const std::complex<float>, std::complex<float>, const int);
chemv_(const char, const int, const std::complex<float>, const std::complex<float>, const int, const std::complex<float>, const int, const std::complex<float>, std::complex<float>, const int);
cher_(const char, const int, const float, const std::complex<float>, const int, std::complex<float>, const int);
cher2_(const char, const int, const std::complex<float>, const std::complex<float>, const int, const std::complex<float>, const int, std::complex<float>, const int);
chpmv_(const char, const int, const std::complex<float>, const std::complex<float>, const std::complex<float>, const int, const std::complex<float>, std::complex<float>, const int);
chpr_(const char, const int, const float, const std::complex<float>, const int, std::complex<float>);
chpr2_(const char, const int, const std::complex<float>, const std::complex<float>, const int, const std::complex<float>, const int, std::complex<float>);
ctbmv_(const char, const char, const char, const int, const int, const std::complex<float>, const int, std::complex<float>, const int);
ctbsv_(const char, const char, const char, const int, const int, const std::complex<float>, const int, std::complex<float>, const int);
ctpmv_(const char, const char, const char, const int, const std::complex<float>, std::complex<float>, const int);
ctpsv_(const char, const char, const char, const int, const std::complex<float>, std::complex<float>, const int);
ctrmv_(const char, const char, const char, const int, const std::complex<float>, const int, std::complex<float>, const int);
ctrsv_(const char, const char, const char, const int, const std::complex<float>, const int, std::complex<float>, const int);
cgem2vc_(const int, const int, const std::complex<float>, const std::complex<float>, const int, const std::complex<float>, const int, const std::complex<float>, const int, const std::complex<float>, std::complex<float>, const int, std::complex<float>, const int);
scgemv_(const char, const int, const int, const std::complex<float>, const float, const int, const std::complex<float>, const int, const std::complex<float>, std::complex<float>, const int);
dgbmv_(const char, const int, const int, const int, const int, const double, const double, const int, const double, const int, const double, double, const int);
dgemv_(const char, const int, const int, const double, const double, const int, const double, const int, const double, double, const int);
dger_(const int, const int, const double, const double, const int, const double, const int, double, const int);
dsbmv_(const char, const int, const int, const double, const double, const int, const double, const int, const double, double, const int);
dspmv_(const char, const int, const double, const double, const double, const int, const double, double, const int);
dspr_(const char, const int, const double, const double, const int, double);
dspr2_(const char, const int, const double, const double, const int, const double, const int, double);
dsymv_(const char, const int, const double, const double, const int, const double, const int, const double, double, const int);
dsyr_(const char, const int, const double, const double, const int, double, const int);
dsyr2_(const char, const int, const double, const double, const int, const double, const int, double, const int);
dtbmv_(const char, const char, const char, const int, const int, const double, const int, double, const int);
dtbsv_(const char, const char, const char, const int, const int, const double, const int, double, const int);
dtpmv_(const char, const char, const char, const int, const double, double, const int);
dtpsv_(const char, const char, const char, const int, const double, double, const int);
dtrmv_(const char, const char, const char, const int, const double, const int, double, const int);
dtrsv_(const char, const char, const char, const int, const double, const int, double, const int);
dgem2vu_(const int, const int, const double, const double, const int, const double, const int, const double, const int, const double, double, const int, double, const int);
zgbmv_(const char, const int, const int, const int, const int, const std::complex<double>, const std::complex<double>, const int, const std::complex<double>, const int, const std::complex<double>, std::complex<double>, const int);
zgemv_(const char, const int, const int, const std::complex<double>, const std::complex<double>, const int, const std::complex<double>, const int, const std::complex<double>, std::complex<double>, const int);
zgerc_(const int, const int, const std::complex<double>, const std::complex<double>, const int, const std::complex<double>, const int, std::complex<double>, const int);
zgeru_(const int, const int, const std::complex<double>, const std::complex<double>, const int, const std::complex<double>, const int, std::complex<double>, const int);
zhbmv_(const char, const int, const int, const std::complex<double>, const std::complex<double>, const int, const std::complex<double>, const int, const std::complex<double>, std::complex<double>, const int);
zhemv_(const char, const int, const std::complex<double>, const std::complex<double>, const int, const std::complex<double>, const int, const std::complex<double>, std::complex<double>, const int);
zher_(const char, const int, const double, const std::complex<double>, const int, std::complex<double>, const int);
zher2_(const char, const int, const std::complex<double>, const std::complex<double>, const int, const std::complex<double>, const int, std::complex<double>, const int);
zhpmv_(const char, const int, const std::complex<double>, const std::complex<double>, const std::complex<double>, const int, const std::complex<double>, std::complex<double>, const int);
zhpr_(const char, const int, const double, const std::complex<double>, const int, std::complex<double>);
zhpr2_(const char, const int, const std::complex<double>, const std::complex<double>, const int, const std::complex<double>, const int, std::complex<double>);
ztbmv_(const char, const char, const char, const int, const int, const std::complex<double>, const int, std::complex<double>, const int);
ztbsv_(const char, const char, const char, const int, const int, const std::complex<double>, const int, std::complex<double>, const int);
ztpmv_(const char, const char, const char, const int, const std::complex<double>, std::complex<double>, const int);
ztpsv_(const char, const char, const char, const int, const std::complex<double>, std::complex<double>, const int);
ztrmv_(const char, const char, const char, const int, const std::complex<double>, const int, std::complex<double>, const int);
ztrsv_(const char, const char, const char, const int, const std::complex<double>, const int, std::complex<double>, const int);
zgem2vc_(const int, const int, const std::complex<double>, const std::complex<double>, const int, const std::complex<double>, const int, const std::complex<double>, const int, const std::complex<double>, std::complex<double>, const int, std::complex<double>, const int);
dzgemv_(const char, const int, const int, const std::complex<double>, const double, const int, const std::complex<double>, const int, const std::complex<double>, std::complex<double>, const int);
sgemm_(const char, const char, const int, const int, const int, const float, const float, const int, const float, const int, const float, float, const int);
ssymm_(const char, const char, const int, const int, const float, const float, const int, const float, const int, const float, float, const int);
ssyr2k_(const char, const char, const int, const int, const float, const float, const int, const float, const int, const float, float, const int);
ssyrk_(const char, const char, const int, const int, const float, const float, const int, const float, float, const int);
strmm_(const char, const char, const char, const char, const int, const int, const float, const float, const int, float, const int);
strsm_(const char, const char, const char, const char, const int, const int, const float, const float, const int, float, const int);
cgemm_(const char, const char, const int, const int, const int, const std::complex<float>, const std::complex<float>, const int, const std::complex<float>, const int, const std::complex<float>, std::complex<float>, const int);
scgemm_(const char, const char, const int, const int, const int, const std::complex<float>, const float, const int, const std::complex<float>, const int, const std::complex<float>, std::complex<float>, const int);
cgemm3m_(const char, const char, const int, const int, const int, const std::complex<float>, const std::complex<float>, const int, const std::complex<float>, const int, const std::complex<float>, std::complex<float>, const int);
chemm_(const char, const char, const int, const int, const std::complex<float>, const std::complex<float>, const int, const std::complex<float>, const int, const std::complex<float>, std::complex<float>, const int);
cher2k_(const char, const char, const int, const int, const std::complex<float>, const std::complex<float>, const int, const std::complex<float>, const int, const float, std::complex<float>, const int);
cherk_(const char, const char, const int, const int, const float, const std::complex<float>, const int, const float, std::complex<float>, const int);
csymm_(const char, const char, const int, const int, const std::complex<float>, const std::complex<float>, const int, const std::complex<float>, const int, const std::complex<float>, std::complex<float>, const int);
csyr2k_(const char, const char, const int, const int, const std::complex<float>, const std::complex<float>, const int, const std::complex<float>, const int, const std::complex<float>, std::complex<float>, const int);
csyrk_(const char, const char, const int, const int, const std::complex<float>, const std::complex<float>, const int, const std::complex<float>, std::complex<float>, const int);
ctrmm_(const char, const char, const char, const char, const int, const int, const std::complex<float>, const std::complex<float>, const int, std::complex<float>, const int);
ctrsm_(const char, const char, const char, const char, const int, const int, const std::complex<float>, const std::complex<float>, const int, std::complex<float>, const int);
dgemm_(const char, const char, const int, const int, const int, const double, const double, const int, const double, const int, const double, double, const int);
dsymm_(const char, const char, const int, const int, const double, const double, const int, const double, const int, const double, double, const int);
dsyr2k_(const char, const char, const int, const int, const double, const double, const int, const double, const int, const double, double, const int);
dsyrk_(const char, const char, const int, const int, const double, const double, const int, const double, double, const int);
dtrmm_(const char, const char, const char, const char, const int, const int, const double, const double, const int, double, const int);
dtrsm_(const char, const char, const char, const char, const int, const int, const double, const double, const int, double, const int);
zgemm_(const char, const char, const int, const int, const int, const std::complex<double>, const std::complex<double>, const int, const std::complex<double>, const int, const std::complex<double>, std::complex<double>, const int);
dzgemm_(const char, const char, const int, const int, const int, const std::complex<double>, const double, const int, const std::complex<double>, const int, const std::complex<double>, std::complex<double>, const int);
zgemm3m_(const char, const char, const int, const int, const int, const std::complex<double>, const std::complex<double>, const int, const std::complex<double>, const int, const std::complex<double>, std::complex<double>, const int);
zhemm_(const char, const char, const int, const int, const std::complex<double>, const std::complex<double>, const int, const std::complex<double>, const int, const std::complex<double>, std::complex<double>, const int);
zher2k_(const char, const char, const int, const int, const std::complex<double>, const std::complex<double>, const int, const std::complex<double>, const int, const double, std::complex<double>, const int);
zherk_(const char, const char, const int, const int, const double, const std::complex<double>, const int, const double, std::complex<double>, const int);
zsymm_(const char, const char, const int, const int, const std::complex<double>, const std::complex<double>, const int, const std::complex<double>, const int, const std::complex<double>, std::complex<double>, const int);
zsyr2k_(const char, const char, const int, const int, const std::complex<double>, const std::complex<double>, const int, const std::complex<double>, const int, const std::complex<double>, std::complex<double>, const int);
zsyrk_(const char, const char, const int, const int, const std::complex<double>, const std::complex<double>, const int, const std::complex<double>, std::complex<double>, const int);
ztrmm_(const char, const char, const char, const char, const int, const int, const std::complex<double>, const std::complex<double>, const int, std::complex<double>, const int);
ztrsm_(const char, const char, const char, const char, const int, const int, const std::complex<double>, const std::complex<double>, const int, std::complex<double>, const int);

cdotc_(std::complex<float>, const int, const std::complex<float>, const int, const std::complex<float>, const int);
cdotu_(std::complex<float>, const int, const std::complex<float>, const int, const std::complex<float>, const int);
zdotc_(std::complex<double>, const int, const std::complex<double>, const int, const std::complex<double>, const int);
zdotu_(std::complex<double>, const int, const std::complex<double>, const int, const std::complex<double>, const int);

} // extern "C"