version: "3"
services:

  vscode:
    image: braintwister/ubuntu-20.04-gcc-10-clang-11-vscode-1.52.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - home:/home/${USER_NAME}
      - ${GIT_DIR}:/home/${USER_NAME}/git
      - ${DATA_DIR}:/home/${USER_NAME}/data
    environment:
      - DISPLAY
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
      - USER_NAME=${USER_NAME}
      - GROUP_NAME=${GROUP_NAME}
    network_mode: host
    ports:
      - 6006:6006

volumes:
  home:
